const data = {
  products: [
    {
      _id: "1",
      name: "Daft Punk",
      title: "Random Access Memories",
      genre: "Electronic",
      image: "/assets/p1.jpeg",
      price: 310,
      nrStock: 10,
      brand: "Columbia/Sony",
      rating: 3,
      nrRating: 25,
      released: "2013",
    },
    {
      _id: "2",
      name: "Wu-Tang Clan",
      title: "Enter the 36 Chambers",
      genre: "Hip Hop",
      image: "/assets/p2.jpeg",
      price: 110,
      nrStock: 15,
      brand: "Independent",
      rating: 2.5,
      nrRating: 33,
      released: "1993",
    },
    {
      _id: "3",
      name: "Guns n Roses",
      title: "Appetite For Destruction",
      genre: "Rock",
      image: "/assets/p3.jpeg",
      price: 199,
      nrStock: 5,
      brand: "Geffen",
      rating: 0.5,
      nrRating: 5,
      released: "1993",
    },
    {
      _id: "4",
      name: "Pink Floyd",
      title: "The Dark Side Of The Moon",
      genre: "Rock",
      image: "/assets/p4.jpeg",
      price: 150,
      nrStock: 5,
      brand: "Capitol",
      rating: 4.6,
      nrRating: 7,
      released: "1973",
    },
    {
      _id: "5",
      name: "Air",
      title: "Moon Safari",
      genre: "Electronic",
      image: "/assets/p5.jpeg",
      price: 99,
      nrStock: 0,
      brand: "Virgin",
      rating: 2.5,
      nrRating: 6,
      released: "1998",
    },
    {
      _id: "6",
      name: "Company Flow",
      title: "Funcrusher Plus",
      genre: "Hip Hop",
      image: "/assets/p6.jpeg",
      price: 299,
      nrStock: 0,
      brand: "Rawkus",
      rating: 3.4,
      nrRating: 23,
      released: "1997",
    },

    {
      _id: "7",
      name: "Abba",
      title: "The Best Of ABBA",
      genre: "Pop",
      image: "/assets/p7.jpeg",
      price: 299,
      nrStock: 21,
      brand: "Polar Music International",
      rating: 4.6,
      nrRating: 23,
      released: "1975",
      //about:
      // '"The Best Of ABBA" is the best-selling album of all time in Australia (tied with Dire Straits Brothers in Arms), certified 22 times Platinum, with over 1,100,000 units sold. In New Zealand it is certified 24 times Platinum. In the Netherlands and West Germany The Best Of ABBA was the best-selling album of 1976. ',
    },
    {
      _id: "8",
      name: "Michael Jackson",
      title: "Thriller",
      genre: "Pop",
      image: "/assets/p8.jpeg",
      price: 199,
      nrStock: 17,
      brand: "by Quincy Jones",
      rating: 4.7,
      nrRating: 133,
      released: "1982",
      // about:
      //  'Every song of the LP, excluding "The Lady In My Life", either charted in the Billboard Top 100 or was issued as an A-side or B-side on 45 RPM singles. It was released on November 30, 1982 as the follow-up to Jackson`s 1979 critically and highly commercially successful Off The Wall LP. Thriller explores similar genres to those that were heard on Off the Wall but redefined pop music, R&B, rock, post-disco, funk, and even adult contemporary music. It currently remains the largest grossing LP and represents the most copies ever sold of one LP worldwide, with sales over 65 million copies according to various sources. ',
    },

    {
      _id: "9",
      name: "Prince And The Revolution",
      title: "Purple Rain",
      genre: "Pop",
      image: "/assets/p9.jpeg",
      price: 399,
      nrStock: 3,
      brand: "by Warner Bros",
      rating: 4.48,
      nrRating: 132,
      released: "1984",
      //  about: 'Awards: Academy Awards/Oscars 1985 (Best Music, Original Song Score) Brit Awards 1985 (Best Soundtrack) Grammy Awards 1985 (Best Album of Instrumental Score written for a Motion Picture or Television Special)',
    },
    {
      _id: "10",
      name: "The Beatles",
      title: "Rubber Soul",
      genre: "Pop",
      image: "/assets/p10.jpeg",
      price: 250,
      nrStock: 2,
      brand: "by George Martin",
      rating: 4.57,
      nrRating: 153,
      released: "1965",
      //  about: 'Rubber Soul is the sixth studio album by the English rock band the Beatles. ... The title derives from the colloquialism "plastic soul" and was the Beatles' way of acknowledging their lack of authenticity compared to the African-American soul artists they admired.',
    },
    {
      _id: "11",
      name: "Queen",
      title: "Gretist Hits",
      genre: "Pop",
      image: "/assets/p11.jpeg",
      price: 200,
      nrStock: 12,
      brand: "by EMI Records",
      rating: 4.6,
      nrRating: 187,
      released: "1980",
      // about:
      //  ' "Greatest Hits" was an instant success, peaking at number one on the UK Album Chart for four weeks. It has spent over 700 weeks in the UK Charts, and is the best-selling album of all time in the UK, selling over 6 million copies there. It is certified 8 x Platinum in the United States, and is Queen`s most commercially successful album worldwide with over 25 million copies sold, making it one of the best-selling albums of all time.',
    },

    {
      _id: "12",
      name: "Golden Earring",
      title: "Switch",
      genre: "Rock",
      image: "/assets/p12.jpeg",
      price: 300,
      nrStock: 11,
      brand: "Music on Vinyl?",
      rating: 3.8,
      nrRating: 23,
      release: "2021",
      //about:
      // '"180 gram audiophile vinyl Includes 4 page insert. Limited first pressing of 1500 individually numbered copies on transparent blue vinyl. Switch is the tenth studio album by Dutch rock band Golden Earring, released in 1975 as the follow-up of the band's international breakthrough album Moontan. Switch actually marked a switch for Golden Earring, as it was more influenced by funk and prog than any of the band's previous or subsequent releases. Lead single “Kill Me (Ce Soir)” perfectly demonstrates how Golden Earring experimented with a new sound. This reissue comes with a 4 page insert. Switch is available as a limited edition of 1500 individually numbered copies on transparent blue vinyl. ',
    },
    {
      _id: "13",
      name: "Evanescence",
      title: "The Bitter Truth: Deluxe Gatefold Vinyl",
      genre: "Rock",
      image: "/assets/p13.jpeg",
      price: 200,
      nrStock: 3,
      brand: "RCA",
      rating: 4.1,
      nrRating: 23,
      release: "2021",
      //about:
      // 'Evanescence’s first album of original music in a decade, The Bitter Truth. The album sees them return to their dark and heavy rock roots. ',
    },
    {
      _id: "14",
      name: "Metallica",
      title: "Master Of Puppets",
      genre: "Rock",
      image: "/assets/p14.jpeg",
      price: 850,
      nrStock: 5,
      brand: "Umc Mercury",
      rating: 4.3,
      nrRating: 127,
      release: "2017",
      //about:
      // 'Titled The Greatest Mistake Of My Life, the upcoming album from the rapidly rising UK post-hardcore band is their second full-length offering and is scheduled to be released in April next year, via SharpTone Records. The upcoming album is the follow-up to 2019’s self-titled full-length debut. Speaking about the upcoming album, the band says, “this album is about telling stories that are presented through the lens of hindsight, regret and looking back. There are songs that celebrate life when faced with death, and others that speak to the choices we make about how we live our lives. The fear of love, newfound respect for life and the covering up of depression are all subjects that rear their head. The Greatest Mistake Of My Life exercises emotion in many ways, and that was an important thing for us to do, because emotion isn’t rigid – it’s not just love or joy or sadness – it’s a lot of things.”',
    },
    {
      _id: "15",
      name: "Holding Absence",
      title: "The Greatest Mistake Of My Life",
      genre: "Rock",
      image: "/assets/p15.jpeg",
      price: 250,
      nrStock: 5,
      brand: "Sharptone",
      rating: 3.2,
      nrRating: 7,
      release: "2021",
      //about:
      // 'Titled The Greatest Mistake Of My Life, the upcoming album from the rapidly rising UK post-hardcore band is their second full-length offering and is scheduled to be released in April next year, via SharpTone Records. The upcoming album is the follow-up to 2019’s self-titled full-length debut. Speaking about the upcoming album, the band says, “this album is about telling stories that are presented through the lens of hindsight, regret and looking back. There are songs that celebrate life when faced with death, and others that speak to the choices we make about how we live our lives. The fear of love, newfound respect for life and the covering up of depression are all subjects that rear their head. The Greatest Mistake Of My Life exercises emotion in many ways, and that was an important thing for us to do, because emotion isn’t rigid – it’s not just love or joy or sadness – it’s a lot of things.”',
    },
  ],
}

export default data

// "about": "Titled The Greatest Mistake Of My Life, the upcoming album from the rapidly rising UK post-hardcore band is their second full-length offering and is scheduled to be released in April next year, via SharpTone Records. The upcoming album is the follow-up to 2019’s self-titled full-length debut. Speaking about the upcoming album, the band says, “this album is about telling stories that are presented through the lens of hindsight, regret and looking back. There are songs that celebrate life when faced with death, and others that speak to the choices we make about how we live our lives. The fear of love, newfound respect for life and the covering up of depression are all subjects that rear their head. The Greatest Mistake Of My Life exercises emotion in many ways, and that was an important thing for us to do, because emotion isn’t rigid – it’s not just love or joy or sadness – it’s a lot of things."
// "about": " Titled The Greatest Mistake Of My Life, the upcoming album from the rapidly rising UK post-hardcore band is their second full-length offering and is scheduled to be released in April next year, via SharpTone Records. The upcoming album is the follow-up to 2019’s self-titled full-length debut. Speaking about the upcoming album, the band says, “this album is about telling stories that are presented through the lens of hindsight, regret and looking back. There are songs that celebrate life when faced with death, and others that speak to the choices we make about how we live our lives. The fear of love, newfound respect for life and the covering up of depression are all subjects that rear their head. The Greatest Mistake Of My Life exercises emotion in many ways, and that was an important thing for us to do, because emotion isn’t rigid – it’s not just love or joy or sadness – it’s a lot of things."
