const data = {
    products: [
        {
            _id: '1',
            name: 'Round Lamp 1',
            category: 'Lamps',
            image: '/assets/p1.jpeg',
            price: 2599,
            nrStock: 10,
            brand: 'Gucci',
            rating: 3,
            nrRating: 25,
            description: 'a round lamp',
        },
        {
            _id: '2',
            name: 'Round Lamp 2',
            category: 'Lamps',
            image: '/assets/p2.jpeg',
            price: 399,
            nrStock: 15,
            brand: 'Sunny Drip',
            rating: 2.5,
            nrRating: 33,
            description: 'a round lamp',
        },
        {
            _id: '3',
            name: 'Round Lamp 3',
            category: 'Lamps',
            image: '/assets/p3.jpeg',
            price: 199,
            nrStock: 5,
            brand: 'BMW',
            rating: 0.5,
            nrRating: 5,
            description: 'a round lamp',
        },
        {
            _id: '4',
            name: 'Round Lamp 4',
            category: 'Lamps',
            image: '/assets/p4.jpeg',
            price: 1599,
            nrStock: 5,
            brand: 'Lights R Us',
            rating: 4.6,
            nrRating: 7,
            description: 'a round lamp',
        },
        {
            _id: '5',
            name: 'Round Lamp 5',
            category: 'Lamps',
            image: '/assets/p5.jpeg',
            price: 99,
            nrStock: 0,
            brand: 'BrightBall',
            rating: 2.1,
            nrRating: 6,
            description: 'a round lamp',
        },
        {
            _id: '6',
            name: 'Round Lamp 6',
            category: 'Lamps',
            image: '/assets/p6.jpeg',
            price: 299,
            nrStock: 0,
            brand: 'Lampville',
            rating: 3.4,
            nrRating: 23,
            description: 'a round lamp',
        },
    ]
}

export default data